<?php

namespace AppBundle\Repository;

use CoreBundle\Repository\CustomRepository;

/**
 * AchatMatierePremiereOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatMatierePremiereOptionRepository extends CustomRepository
{
}
