<?php

namespace AppBundle\Repository;

/**
 * AchatMatierePremiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatMatierePremiereRepository extends \Doctrine\ORM\EntityRepository
{
}
