<?php

namespace AppBundle\Repository;

/**
 * AchatEmbalageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatEmbalageRepository extends \Doctrine\ORM\EntityRepository
{
}
