<?php

namespace AppBundle\Repository;

/**
 * AchatMatierePremiereOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatMatierePremiereOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
