<?php

namespace AppBundle\Repository;

/**
 * AchatMatierePremiereProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatMatierePremiereProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
