<?php

namespace AppBundle\Repository;

/**
 * ChargeEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargeEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
