<?php

namespace AppBundle\Repository;

/**
 * EDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
