<?php

namespace AppBundle\Repository;

/**
 * EmbalageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmbalageRepository extends \Doctrine\ORM\EntityRepository
{
}
