<?php

namespace AppBundle\Repository;

use CoreBundle\Repository\CustomRepository;

/**
 * ModePaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModePaymentRepository extends CustomRepository
{
    function listeDataTable(array $criteres, $sort, $dir, $start = 0, $max = 25) {
        $qb = $this->_em->createQueryBuilder();
        $qb->from($this->_entityName, "m");

        $total = $qb->select("COUNT(m)")->getQuery()->getSingleScalarResult();
        $operateur = 'where';

        if(isset($criteres['id'])){
            $qb
                ->$operateur('m.id = :id')
                ->setParameter('id',$criteres['id'])
            ;
            $operateur = 'andWhere';
        }
       if(isset($criteres['label'])){
            $qb
                ->$operateur('m.label LIKE :label')
                ->setParameter('label',"%".$criteres['label']."%")
            ;
            $operateur = 'andWhere';
        }
        if (isset($criteres["archive"])) {
            $qb->$operateur("m.archive = :archive")
                ->setParameter("archive", $criteres["archive"])
            ;
            $operateur = "andWhere";
        }

        $totalFiltred = $qb->select("COUNT(m)")->getQuery()->getSingleScalarResult();

        $modes = $qb
            ->select("DISTINCT m")
            ->setFirstResult($start)
            ->setMaxResults($max)
            ->orderBy($sort, $dir)
            ->getQuery()->getResult()
        ;
        return array("total" => $total, "totalFiltred" => $totalFiltred, "modes" => $modes);
    }
}
