<?php

namespace AppBundle\Repository;

/**
 * ProduitEntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitEntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
}
