<?php

namespace AppBundle\Repository;

use CoreBundle\Repository\CustomRepository;

/**
 * ProduitCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitCommandeRepository extends CustomRepository
{
    function ventes($mois,$annee){
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('p.titre AS produit,p.unite,IFNULL(SUM(pc.quantite),0) AS vente')
            ->from($this->getEntityName(),'pc')
            ->join('pc.commande','c')
            ->join('pc.produit','p')
            ->where('month(c.date) = :mois')
            ->andWhere('year(c.date) = :annee')
            ->setParameter('mois',$mois)
            ->setParameter('annee',$annee)
            ->groupBy('produit')
        ;
        return $qb->getQuery()->getResult();
    }
}
