<?php

namespace AppBundle\Repository;

use CoreBundle\Repository\CustomRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends CustomRepository
{
    function listeDataTable($currentUserId,$find, $sort, $dir, $start = 0, $max = 10) {
        $qb = $this->_em->createQueryBuilder();
        $qb->from($this->_entityName, "u");

        $total = $qb->select("COUNT(u)")->getQuery()->getSingleScalarResult();

        $qb
            ->where("u.id <> :idUser")
            ->setParameter("idUser",$currentUserId)
        ;
        if ($find) {
            $qb->andWhere("(u.username LIKE :find OR u.email LIKE :find)")
                ->setParameter("find", "%" . $find . "%")
            ;
        }

        $totalFiltred = $qb->select("COUNT(u)")->getQuery()->getSingleScalarResult();

        $users = $qb
            ->select("DISTINCT u")
            ->setFirstResult($start)
            ->setMaxResults($max)
            ->orderBy($sort, $dir)
            ->getQuery()->getResult()
        ;
        return array("total" => $total, "totalFiltred" => $totalFiltred, "users" => $users);
    }
}
