services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.fournisseur.manager:
        class: AppBundle\Manager\FournisseurManager
        arguments: ["@doctrine.orm.entity_manager"]
